### ISSUE TITLE
Offset issues

### ISSUE THREAD

**Issue by maclyn** [adicu/density#99]
I was trying to write the documentation for Density and ran a few test queries, and I got the "admin was notified error". I think my query, which was http://density.adicu.com/window/2014-10-10T08:00/2014-10-10T21:30/building/75?auth_token=[real auth token], was in the right format (if not, we should return an error for invalid parameter(s).

The error was:

Traceback (most recent call last):
  File "/srv/adi-density/www/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/adi-density/www/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/adi-density/www/density/density.py", line 90, in authorization_checker
    return func(*args, **kwargs)
  File "/srv/adi-density/www/density/density.py", line 300, in get_window_building_data
    new_offset = offset + db.QUERY_LIMIT
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int

**Comment by thebrianzeng** [comment]
yeah i got the errors - try it again now, it should be fixed

**Comment by maclyn** [comment]
Great, it seems to work again. I was getting errors for the day route as well; I'm not sure if that's related...

**Comment by maclyn** [comment]
I think we can close this now. It seems to be fixed. :closed_book:
